/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Car = IDL.Record({
  'id' : IDL.Nat,
  'model' : IDL.Text,
  'make' : IDL.Text,
  'year' : IDL.Nat,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'priceUSD' : IDL.Nat,
  'horsepower' : IDL.Nat,
  'engine' : IDL.Text,
});
export const Inquiry = IDL.Record({
  'id' : IDL.Nat,
  'carId' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  'getCar' : IDL.Func([IDL.Nat], [IDL.Opt(Car)], ['query']),
  'getCars' : IDL.Func([], [IDL.Vec(Car)], ['query']),
  'getInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'submitInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Int],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Car = IDL.Record({
    'id' : IDL.Nat,
    'model' : IDL.Text,
    'make' : IDL.Text,
    'year' : IDL.Nat,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'priceUSD' : IDL.Nat,
    'horsepower' : IDL.Nat,
    'engine' : IDL.Text,
  });
  const Inquiry = IDL.Record({
    'id' : IDL.Nat,
    'carId' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    'getCar' : IDL.Func([IDL.Nat], [IDL.Opt(Car)], ['query']),
    'getCars' : IDL.Func([], [IDL.Vec(Car)], ['query']),
    'getInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'submitInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Int],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };