/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Car {
  'id' : bigint,
  'model' : string,
  'make' : string,
  'year' : bigint,
  'description' : string,
  'category' : string,
  'priceUSD' : bigint,
  'horsepower' : bigint,
  'engine' : string,
}
export interface Inquiry {
  'id' : bigint,
  'carId' : bigint,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
}
export interface _SERVICE {
  'getCar' : ActorMethod<[bigint], [] | [Car]>,
  'getCars' : ActorMethod<[], Array<Car>>,
  'getInquiries' : ActorMethod<[], Array<Inquiry>>,
  'submitInquiry' : ActorMethod<
    [string, string, string, bigint, bigint],
    bigint
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];