/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Float64,
});

export const idlService = IDL.Service({
  'getCoatByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getCoatById' : IDL.Func([IDL.Nat], [Product], ['query']),
  'listCoats' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Int],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Float64,
  });
  
  return IDL.Service({
    'getCoatByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'getCoatById' : IDL.Func([IDL.Nat], [Product], ['query']),
    'listCoats' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Int],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };